---
  # Reiquired vars
  # vt_uid
  # vt_keyspace
  # vt_shard
  # vt_tablet_type
  # vt_deploy_host
  # vttablet_alias
- name: Put variables
  set_fact:
    vttablet_dir: "{{ vt_dir }}/vttablet-{{ vttablet_alias }}"
    vttablet_port: "{{ 15000 + (vt_uid | int) }}"
    vttablet_grpc_port: "{{ 16000 + (vt_uid | int) }}"
    vttablet_mysql_port: "{{ 17000 + (vt_uid | int) }}"

- name: Put variables2
  set_fact:
    vttablet_syslog_dir: "{{ vttablet_dir }}/syslog"
    vttablet_data_dir: "{{ vttablet_dir }}/data"

- name: Create required directories1
  file: path="{{ vttablet_dir }}" owner=vitess group=vitess state=directory mode=0755
  become: yes

- name: Create required directories2
  file: path="{{ vttablet_syslog_dir }}" owner=vitess group=vitess state=directory mode=0755
  become: yes

- name: Create required directories3
  file: path="{{ vttablet_data_dir }}" owner=vitess group=vitess state=directory mode=0755
  become: yes

- name: Put mysql conf file
  template:
    src: additional.my.cnf.j2
    dest: "{{ vttablet_data_dir }}/additional.my.cnf"
    owner: vitess
    group: vitess 
    mode: 0644
  become: yes

- name: Create compose dir
  file: path="{{ docker_compose_dir }}/vttablet-{{ vttablet_alias }}" state=directory mode=0755
  become: yes

- name: Put tablet compose yml
  template:
    src: vttablet-compose.yml.j2
    dest: "{{ docker_compose_dir }}/vttablet-{{ vttablet_alias }}/docker-compose.yml"
    mode: 0644
  become: yes

- name: Compose vttablet service up
  args:
    chdir: "{{ docker_compose_dir }}/vttablet-{{ vttablet_alias }}"
  command: docker-compose up -d
