---
- hosts: all
  roles:
    - common
    - docker

- hosts: etcd
  roles:
    - etcd

- hosts: vtnode
  roles:
    - vt-common

- hosts: manage
  roles:
    - vtctld
    - vtctlclient

- hosts: vtgate
  roles:
    - vtgate
