---
- name: Create required directories
  file:
    path: "{{ item }}"
    owner: vitess
    group: vitess
    state: directory
    mode: 0755
  with_items:
    - "{{ vtgate_dir }}"
    - "{{ vtgate_syslog_dir }}"
    - "{{ vtgate_data_dir }}"
    - "{{ docker_compose_dir }}/vtgate"
  become: yes

- name: Put vtgate compose yml
  template:
    src: vtgate-compose.yml.j2
    dest: "{{ docker_compose_dir }}/vtgate/docker-compose.yml"
    mode: 0644
  become: yes

- name: Compose vtgate service up
  args:
    chdir: "{{ docker_compose_dir }}/vtgate"
  command: docker-compose up -d
