---
- name: Create required directories
  file:
    path: "{{ item }}"
    owner: vitess
    group: vitess
    state: directory
    mode: 0755
  with_items:
    - "{{ vtctld_dir }}"
    - "{{ vtctld_syslog_dir }}"
    - "{{ vtctld_data_dir }}"
    - "{{ docker_compose_dir }}/vtctld"
  become: yes

- name: Put vtctld compose yml
  template:
    src: vtctld-compose.yml.j2
    dest: "{{ docker_compose_dir }}/vtctld/docker-compose.yml"
    mode: 0644
  become: yes

- name: Compose vtctld service up
  args:
    chdir: "{{ docker_compose_dir }}/vtctld"
  command: docker-compose up -d
