---
- name: Create etcd directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ etcd_data_dir }}"
    - "{{ etcd_conf_dir }}"
    - "{{ docker_compose_dir }}/etcd"
  become: yes

- name: Put etcd conf
  template:
    src: etcd.yml.j2
    dest: "{{ etcd_conf_dir }}/etcd.yml"
    mode: 0644
  become: yes

- name: Put etcd compose yml
  template:
    src: etcd-compose.yml.j2
    dest: "{{ docker_compose_dir }}/etcd/docker-compose.yml"
    mode: 0644
  become: yes

- name: Compose etcd service up
  args:
    chdir: "{{ docker_compose_dir }}/etcd"
  command: docker-compose up -d
