---
- name: Create etcd directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ etcd_root }}"
    - "{{ etcd_conf_dir }}"
  become: yes

- name: Put etcd conf
  template:
    src: etcd.yml.j2
    dest: "{{ etcd_conf_dir }}/etcd.yml"
    mode: 0644
  notify: Restart etcd
  become: yes

- name: Put etcd compose yml
  template:
    src: docker-compose.yml.j2
    dest: "{{ etcd_root }}/docker-compose.yml"
    mode: 0644
  become: yes

- name: etcd service up
  docker_service:
    project_src: "{{ etcd_root }}"
    state: present
