---
- name: Create etcd directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "{{ etcd_data_dir }}"
    - "{{ etcd_conf_dir }}"
  become: yes

- name: Put etcd conf
  template:
    src: etcd.yml.j2
    dest: "{{ etcd_conf_dir }}/etcd.yml"
    mode: 0644
  become: yes

- name: Start etcd
  docker_container:
    name: etcd
    image: "{{ etcd_docker_tag }}"
    state: started
    ports:
      - "{{ etcd_advertise_port }}:2379"
      - "2380:2380"
    volumes:
      - "{{ etcd_data_dir }}:{{ etcd_data_dir }}"
      - "{{ etcd_conf_dir }}:{{ etcd_conf_dir }}"
    command: "etcd --config-file {{ etcd_conf_dir }}/etcd.yml" 
