---
vt_uid: 3030
vt_gid: 3030

vt_vitess_version: v2.0.0
vt_docker_tag: "vitess/lite:{{ vt_vitess_version }}"
vt_env_vtroot: /vt
# vt_env_vttop: "{{ vt_env_vtroot }}/src/github.com/youtube/vitess"
vt_env_vtdataroot: "{{ vt_env_vtroot }}/vtdataroot"
vt_env_topology_flags:
  - "-topo_implementation etcd"
  - "-etcd_global_addrs {{ vt_etcd_addrs | join(',') }}"

vt_dir: /var/vt
