---
- name: Check already installed
  stat: path=/usr/local/bin/lvtctl
  register: lvtctl_stat

- block:
  - name: go get
    command: go get github.com/youtube/vitess/go/cmd/vtctlclient
    environment: "{{ go_path_env }}"

  - name: Put lvtctl.sh
    template:
      src: lvtctl.sh.j2
      dest: /usr/local/bin/lvtctl
      mode: 0755
    become: yes

  when: not lvtctl_stat.stat.exists
